pipeline {
    agent any

    environment {
        HOME = "${WORKSPACE}"
        GOPATH = "${WORKSPACE}/go"
        GOCACHE = "${WORKSPACE}/.cache/go-build"
        GOMODCACHE = "${WORKSPACE}/go/pkg/mod"
    }

    stages { 

        stage('Execute Unit Tests') {
            parallel {

                stage('Unit Tests - Backend') {
                    agent {
                        docker {
                            image 'snakee/golang-junit:1.21'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-backend') {
                            sh 'go test -v ./...'
                            
                            sh '''
                                # Generate coverage report
                                go test -coverprofile=coverage.out -covermode=atomic ./...
                                go tool cover -html=coverage.out -o coverage.html

                                mkdir -p reports
                                mv coverage.html reports/report.xml
                            '''
                        }
                    }

                    post {
                        always {
                            junit 'bugtracker-backend/reports/report.xml'
                            publishHTML target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'bugtracker-backend/reports',
                        reportFiles: 'coverage.html',
                        reportName: 'Backend Coverage Report'
                        ]
                        }
                    }
                }

                stage('Unit Tests - Frontend') {
                    agent {
                        docker {
                            image 'node:20-alpine'
                            reuseNode true
                        }
                    }
                    steps {
                        dir('bugtracker-frontend') {
                            sh '''
                                npm ci
                                npm test
                                mkdir -p reports
                                mv coverage reports/
                            '''
                        }
                    }

                    post {
                        always {
                            junit 'bugtracker-frontend/test-results.xml'

                            publishHTML target: [
                                allowMissing: true,
                                alwaysLinkToLastBuild: true,
                                keepAll: true,
                                reportDir: 'bugtracker-frontend/reports/coverage',
                                reportFiles: 'index.html',
                                reportName: 'Frontend Coverage Report'
                            ]
                        }
                    }
                }
            }
        }

        stage('Launch application') {
    
            agent  {
                docker {
                    image 'docker:27.5.1'
                    reuseNode true
                    args '-v /var/run/docker.sock:/var/run/docker.sock -u 0'
                }
            }

            steps {
                sh 'docker compose up --build -d'
            }
        }

        stage('API tests') {
            agent {
                docker {
                    image 'mcr.microsoft.com/playwright:v1.50.0-jammy'
                    reuseNode true
                    args '-u 0 --network=host'  // Runs container as root, also local network
                }
            }

            steps {
                dir('tests-api') {
                    sh 'npx wait-port http://localhost:8080/api/health -t 30000'

                    sh 'npm ci'
                    sh 'npx playwright test'
                }
            }
         }

        post {
            always {
                cleanWs()
            }
        }
    }
}